### ISSUE TITLE
Grammar Update

### ISSUE THREAD

**Issue by kylehoover** [xeger/language-kerboscript#3]
Any chance of this getting updated to include some newer language features? Two keywords that I've noticed aren't in the grammar are `is` and `wait`. I haven't created a grammar for Atom before, but if you guys don't have time/slash don't want to work on this, but are open to PRs, then I could look into adding some of the stuff that's missing.

**Comment by kylehoover** [comment]
I should have read the README more closely! It clearly says that contributions are welcome. I've forked the repo and am currently working on adding the changes I mentioned.

**Comment by dfrison01** [comment]
Hi @kylehoover !
I'm a newbie, but i'd like to contribute. Is this repo being maintained?
RETURN and WAIT are currently not highlited, for example. Should I create a request here, or work on your fork?
Thx in advance!

**Comment by kylehoover** [comment]
I don't think this repo is being maintained anymore, so I'm not sure making a request here will get a response. I stopped working on my fork after finding [kos-language-server](https://github.com/jonnyboyC/kos-language-server), which I use with VS Code. Beyond syntax highlighting, it also offers code completion and other really great features. It's being actively maintained and the repo's owner is quick to respond to issues. It also has syntax highlighting for Atom if you don't want to use VS Code. Hope that helps!
